Improve chat panel
DominicMaas/Tango pull request #200
Opened 2020-10-04 22:23 UTC by lgoenner

Closes #199

The chat can now easily be opened and closed, without any of the old /hide-chat stuff. 
Press T to open, escape or an empty message to close.

I haven't tried this in multiplayer though, since my computer can't run two instances of the game.
The bug where it sometimes  cuts off some of the text at the bottom still occurs.

2020-10-05 18:54 UTC, kaenganxt requested changes
Thank you for your contribution! Looks mostly good (And also works in multiplayer :)). Just a small text improvement.

While testing I noticed that it would be quite nice if the chat disappeared after a certain amount of time (e.g. 5 seconds). Would you like to add this to this PR? If you don't want to add it, or want to do it later, I'm happy to merge this PR as it is.

2020-10-05 18:54 UTC, kaenganxt commented on src/Panels/ChatLogPanel.cs
> +            PrintGameMessage("Press the T key to show the chat.");
Please add a text that the Chat can be hidden with the Esc key.

2020-10-06 17:56 UTC, lgoenner commented
Please merge the PR as is. I might add the automatic closing at a later date (can't promise anything), but I first want to try adding TMPE support or some syncing stuff.

2020-10-06 18:01 UTC, kaenganxt approved these changes
Looks good, thank you!

2020-10-06 18:02 UTC, merged