Bypassed version checks that are bound to steam. Temporary fix for Ep…
DominicMaas/Tango pull request #211
Opened 2020-12-18 19:07 UTC by tomtehtom

Temporary fix for Epic players desperate to cross-play.

2020-12-18 20:47 UTC, BluePhoenixGame requested changes
I really don't think this can be accepted into the mod, surely we have to get an actual fix working.

2020-12-18 20:47 UTC, BluePhoenixGame commented on src/Commands/Handler/Internal/ConnectionRequestHandler.cs
> +            if (command.GameVersion != command.GameVersion)
Obviously this can't be an accepted solution

2020-12-18 20:47 UTC, BluePhoenixGame commented on src/Commands/Handler/Internal/ConnectionRequestHandler.cs
> +            if (command.ModVersion != command.ModVersion)
Like the other "fix", this really can't be an accepted solution.

2020-12-18 21:07 UTC, DominicMaas commented
We don't want to disable the mod version check (things will get real messy). You will need to download the matching release for Steam (and if required I can publish a new Steam version). 

With the game version check, we might be able to get away with just checking Major.Minor, but I'm unsure. Disabling the version check completely will cause too many issues in the future.

2020-12-18 23:38 UTC, BluePhoenixGame commented
Assuming Paradox stays sane, and continue semantic versioning the game correctly, we can expect the `BuildConfig.applicationVersion` to be `X.Y.Z-W`. But for the epic games version it just seems that they added the `-eV` ( V stands for the Epic Games version? ) suffix. Stripping this from the string safely should result in a good comparison.

For the second change with the `versionString` variable and the actual mod check, this change shouldn't be needed. I don't think anything broke with the introduction of an Epic Games version, for the mod versioning at least.

2020-12-19 00:31 UTC, tomtehtom commented
Really appreciate the enthusiastic responses. Great to know some amazing people put hard work into an open source project for the community. First off thanks a bunch to you guys for this.

The mod versioning bypass was because my friend with the most up to date steam workshop game+mod was getting a different client/server error which I bypassed by botching the if check.

The mod bypass wasn't meant to be in the commit, was laziness on my part that he couldn't be bothered to install the mod outside of workshop so I just hoped there weren't too many differences in mod updates. Perhaps don't push updates to GitHub master until workshop is ready to be pushed.

I would have worked on a more robust version checker myself, I too noticed the end tag for epic games. But I've only just finished learning Java and I didn't have my IDE setup for C so did it in text editor 😅

Thanks for feedback guys, I'm not that upset my first pull request got rejected. Perhaps I'll submit a proper fix in future to contribute 😉

Note: My temp fix is working flawlessly 😄 just wanted to give people who had the ability a chance to download my code in the meantime as a temp beta thing.

2020-12-19 01:09 UTC, BluePhoenixGame commented
This pull request is not closed or rejected, you are free to continue pushing commits to [tomtehtom:Epic/Steam-TEMP-FIX](https://github.com/tomtehtom/CSM/tree/Epic/Steam-TEMP-FIX). Doing so means that the commits show up in this pull request, so you can continue work here.

Otherwise you can close this yourself if you don't want to look into it a bit more and get an actual fix working.

2020-12-19 20:30 UTC, kaenganxt commented
Fixed in #214 
Since the build script is not yet fixed, feel free to open a pull request for that one.

2020-12-19 20:30 UTC, closed without merging