Synchronise
DominicMaas/Tango pull request #274
Opened 2022-04-20 08:48 UTC by CWMlolzlz

2022-04-20 09:10 UTC, CWMlolzlz commented
@kaenganxt I accidentally created this without setting it to draft. Would you be able to change this to a draft, I don't think I have permission

2022-07-16 19:17 UTC, kaenganxt commented
What's the state on this? Are only the three remaining tools missing before this is ready?

2023-01-09 01:05 UTC, RuisSoftware commented
Please continue working on this pull request :)

2023-03-12 21:40 UTC, kaenganxt commented
I changed/implemented the following things in my new commits:
- Move tool handlers to basegame project
- Implement the district tool
- Fix some default cursors
- Remove old player pointer logic
- Make tool commands non-transactional
- Remove some debug code
- Add some null checks to UI logic
- Don't use the color red for other players
- Display brushes correctly
- Fix packet equality checks to prevent spamming
- Fix net tool showing angles forever
- Destroy old cursor objects to prevent exceptions on unload

The transport tool implementation is still not working correctly, but this is caused by the basic transport line synchronisation being bugged when two players build lines at the same time.

The disaster tool will be looked at when implementing DLC features.

The PR should build correctly once the Cities assemblies are up to date.

2023-03-13 22:47 UTC, DominicMaas commented
I'll update the assemblies when I get home this afternoon

2023-03-14 07:41 UTC, DominicMaas commented
Updated the assemblies, lets see how this goes

2023-04-09 01:05 UTC, hibo98 requested changes

2023-04-09 01:05 UTC, hibo98 commented on src/api/Networking/Player.cs
> +﻿using System;
unused import

2023-04-09 01:05 UTC, hibo98 commented on src/basegame/Injections/Tools/DistrictToolHandler.cs
> +        }
Check for using spaces instead of tabs

2023-04-09 01:05 UTC, hibo98 commented on src/csm/CSM.cs
> +using CSM.Networking;
unused imports

2023-04-09 01:05 UTC, hibo98 commented on src/csm/Networking/MultiplayerManager.cs
> +using CSM.API.Networking;
unused import

2023-04-09 01:17 UTC, hibo98 approved these changes

2023-04-09 01:21 UTC, merged