Implement joining over Steam
DominicMaas/Tango pull request #303
Opened 2023-02-05 02:01 UTC by kaenganxt

This PR implements joining over the Steam friend list based on #159 

- Check for availability of steam_api64.dll or steam_api.dll and enable Steam feature accordingly
- Set Steam rich presence values when acting as server or client:
  - status: The fact that the user is playing on a server
  - connect: A connection token to enable the "Join Game" button in the friend list
  - steam_player_group: The same token identifying the current server, this will group all players on the same server in the friend list
  - steam_player_group_size: The number of players on the server (Will show "+X other players" in the friend list grouping)

For other friends it looks like this:
![grafik](https://user-images.githubusercontent.com/2989730/216797602-3d6f2f69-abb4-402f-ab44-46436d64d476.png)
(The text at the bottom says "Playing with 1 other player")
- Implement server tokens
  - Server generates random token
  - Token is sent to joining clients
  - All members provide the token to Steam
  - The token is registered on the API server
  - Joining over Steam then works with the token instead of an IP address and port
- Read command line once in main menu to allow joining over the friend list even if the game is not running
- Listen for Steam rich presence join requests
- Include certain copied files from Steamworks.NET to implement the callback listener
- Make API server port configurable

To test this PR, change the API server port to 4250.

2023-02-05 22:35 UTC, DominicMaas commented
Oh wow!

2023-04-09 00:17 UTC, hibo98 requested changes

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Networking/Config/ClientConfig.cs
> +        public string Token;
Variable documentation

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Commands/Handler/Internal/ClientConnectHandler.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", MultiplayerManager.Instance.PlayerList.Count.ToString());
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Commands/Handler/Internal/ClientDisonnectHandler.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", MultiplayerManager.Instance.PlayerList.Count.ToString());
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Commands/Handler/Internal/ConnectionResultHandler.cs
> +                    SteamHelpers.Instance.SetRichPresence("steam_player_group", command.ServerToken);
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Commands/Handler/Internal/PlayerListHandler.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", MultiplayerManager.Instance.PlayerList.Count.ToString());
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Helpers/SteamHelpers.cs
> +        public static SteamHelpers Instance;
Make setter private

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Networking/Server.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", "1");
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Networking/Server.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", MultiplayerManager.Instance.PlayerList.Count.ToString());
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Networking/Server.cs
> +                SteamHelpers.Instance.SetRichPresence("steam_player_group_size", MultiplayerManager.Instance.PlayerList.Count.ToString());
Make separate methods without magic values

2023-04-09 00:17 UTC, hibo98 commented on src/csm/Panels/ConnectionPanel.cs
> +                    SteamHelpers.Instance.OpenSteamOverlay("friends");
Make separate methods without magic values

2023-04-09 00:43 UTC, hibo98 approved these changes

2023-04-09 00:46 UTC, merged